import gmLogo from "figma:asset/661f558dc14c79fa090b7039a885f26b843f5c04.png";

const e = (v: unknown) => String(v ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const rp = (v: unknown) => Number(v || 0).toLocaleString('en-US', { maximumFractionDigits: 0 });
const rom = (i: number) => ['I','II','III','IV','V','VI','VII','VIII','IX','X'][i] || String(i + 1);
const dataUrl = async (url: string) => {
  if (url.startsWith('data:')) return url;
  const blob = await (await fetch(url)).blob();
  return await new Promise<string>((ok, no) => { const r = new FileReader(); r.onload=()=>ok(String(r.result)); r.onerror=no; r.readAsDataURL(blob); });
};

const normalize = (q: any) => {
  const rawSections = q.sections?.length ? q.sections : [{ nama: q.jenisQuotation === 'Jasa' ? 'Jasa Kerja' : 'Material / Equipment', items: q.items || q.materials || [] }];
  const sections = rawSections.map((s: any) => ({ name:s.nama||s.title||s.label||'Keterangan', items:(s.items||[]).map((x:any) => {
    const qty=Number(x.qty??x.quantity??x.jumlah??0), unitPrice=Number(x.hargaJualUnit??x.hargaUnit??x.unitPrice??0);
    return { description:x.keterangan||x.description||x.materialName||x.nama||'-', specification:x.subKeterangan||x.specification||(Array.isArray(x.specifications)?x.specifications.join('\n'):''), qty, unit:x.satuan||x.unit||'Lot', unitPrice, total:Number(x.hargaJual??x.totalPrice??x.total??qty*unitPrice) };
  }) }));
  const subtotal=Number(q.totalSebelumDiskon??q.subtotal??sections.flatMap((s:any)=>s.items).reduce((a:number,x:any)=>a+x.total,0));
  const discountPercent=Number(q.pricingConfig?.discountPercent??q.diskonPersen??q.discountPercent??0), discount=Number(q.diskonNominal??q.discount??subtotal*discountPercent/100);
  const includePPN=q.pricingConfig?.includePPN??q.includePpn??Number(q.ppn??q.tax??0)>0, taxPercent=Number(q.ppnPercent??q.taxPercent??11), tax=Number(q.ppn??q.tax??(includePPN?(subtotal-discount)*taxPercent/100:0));
  const type=q.jenisQuotation||(/equipment|mesin|alat/i.test(`${q.perihal||''} ${sections.map((s:any)=>s.name).join(' ')}`)?'Equipment':'Material');
  const terms=q.commercialTerms||q.paymentTerms||q.terms||[];
  return {...q,sections,subtotal,discountPercent,discount,taxPercent,tax,grandTotal:Number(q.grandTotal??subtotal-discount+tax),type,no:q.noPenawaran||q.nomorQuotation||q.noQuotation||'-',customer:q.perusahaan||q.kepada||q.customer?.nama||q.customerName||'-',city:q.kotaCustomer||q.lokasi||q.customer?.alamat||q.customerAddress||'',attention:q.up||q.untukPerhatian||q.customer?.pic||q.customerContact||'',signer:q.namaPenandatangan||'Syamsudin',signCity:q.kotaPenandatangan||'Bekasi',opening:q.paragrafPembuka||`Sehubungan dengan permintaan Bapak/Ibu mengenai ${q.perihal||'penawaran harga'}, maka dengan ini kami ajukan penawaran sebagai berikut :`,terms:Array.isArray(terms)?terms:[terms]};
};

export const generateQuotationWordDocument = async (quotation:any) => {
  const q=normalize(quotation), logo=await dataUrl(gmLogo), grouped=q.type==='Jasa'||q.sections.length>1; let n=0;
  const rows=q.sections.map((s:any,si:number)=>{
    const items=s.items.map((x:any,ii:number)=>{ n++; return `<tr><td class="no">${grouped?(ii===0?rom(si):''):n}</td><td class="desc">${grouped?`<span class="subno">${ii+1}</span>`:''}${ii===0&&grouped?`<b>${e(s.name)}</b><br>`:''}${e(x.description)}${x.specification?`<br><span class="spec">${e(x.specification).replace(/\n/g,'<br>')}</span>`:''}</td><td class="price"><span>Rp</span><span>${rp(x.unitPrice)}</span></td><td class="qty">${rp(x.qty)}&nbsp; ${e(x.unit)}</td><td class="price"><span>Rp</span><span>${rp(x.total)}</span></td></tr>`;}).join('');
    const st=s.items.reduce((a:number,x:any)=>a+x.total,0); return items+(grouped?`<tr class="subtotal"><td colspan="3"></td><td>Total ${rom(si)}</td><td class="price"><b>Rp</b><b>${rp(st)}</b></td></tr>`:'');
  }).join('');
  const summary=`<tr class="sum"><td colspan="3"></td><td><b>Total</b></td><td class="price"><b>Rp</b><b>${rp(q.subtotal)}</b></td></tr>${q.discount>0?`<tr class="sum"><td colspan="3"></td><td><b>Diskon ${q.discountPercent}%</b></td><td class="price"><b>Rp</b><b>${rp(q.discount)}</b></td></tr>`:''}${q.tax>0?`<tr class="sum"><td colspan="3"></td><td><b>PPN ${q.taxPercent}%</b></td><td class="price"><b>Rp</b><b>${rp(q.tax)}</b></td></tr>`:''}<tr class="sum grand"><td colspan="3"></td><td><b>Grand Total</b></td><td class="price"><b>Rp</b><b>${rp(q.grandTotal)}</b></td></tr>`;
  const dt=new Date(q.tanggal||Date.now()).toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'}), terms=q.terms.filter(Boolean).length?q.terms:['Harga belum termasuk PPN 11%.','Pembayaran sesuai kesepakatan pada Purchase Order.','Masa berlaku penawaran 4 minggu.'];
  return `<!DOCTYPE html><html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word"><head><meta charset="utf-8"><xml><w:WordDocument><w:View>Print</w:View><w:Zoom>100</w:Zoom></w:WordDocument></xml><style>
  @page{size:A4;margin:16mm}body{font-family:"Times New Roman",serif;font-size:11pt;line-height:1.18;color:#000}table{border-collapse:collapse}.head{width:100%;border:0}.head td{border:0;padding:0;vertical-align:middle}.logo{width:105pt}.company{padding-left:8pt!important;font-style:italic}.name{font-size:17pt;line-height:1}.business{font-size:11pt}.contact{font-size:10pt;line-height:1.1}.rule{border-top:3pt solid #000;margin:5pt 0 2pt}.meta{width:100%;margin-bottom:12pt}.meta td{border:0;padding:1pt 3pt;vertical-align:top}.label{width:75pt}.colon{width:8pt}.recipient p,.opening p,.sign p{margin:0 0 2pt}.recipient{margin-bottom:12pt}.opening{margin-bottom:3pt}.items{width:100%;table-layout:fixed;font-size:10.5pt}.items th,.items td{border-left:1pt solid #000;border-right:1pt solid #000;padding:2pt 3pt;vertical-align:top}.items th{border-top:1pt solid #000;border-bottom:1pt solid #000;text-align:center}.items .no{width:5%;text-align:center}.items .desc{width:48%}.items .qty{width:13%;text-align:center}.price{width:17%}.price span,.price b{display:inline-block}.price span:first-child,.price b:first-child{width:22%}.price span:last-child,.price b:last-child{width:76%;text-align:right}.subno{display:inline-block;width:15pt}.spec{font-size:10pt}.subtotal td{border-top:1pt solid #000;border-bottom:1pt solid #000}.sum td:first-child{border-left:0!important;border-bottom:0!important}.grand td{border-bottom:1pt solid #000!important}.terms{margin-top:9pt}.terms p{font-weight:bold;margin:0 0 3pt}.terms ul{list-style:none;padding:0;margin:0}.terms li{margin:0 0 2pt 12pt;text-indent:-10pt}.closing{margin-top:16pt}.sign{margin-top:12pt}.space{height:52pt}.signer{text-decoration:underline}</style></head><body>
  <table class="head"><tr><td style="width:110pt"><img class="logo" src="${logo}"></td><td class="company"><div class="name">GEMA TEKNIK PERKASA</div><div class="business">REFRACTORY FURNACE AND BOILER</div><div class="contact">Jl. Nurushoba II No 13 Setia Mekar Tambun Selatan Bekasi 17510<br>Phone : 085 100 420 221 , 021.88354 139&nbsp;&nbsp; Fax : 021.88354 139<br>Email : <span style="color:#00f">gemateknik@gmail.com</span>${q.type==='Jasa'?'<br>Website : <span style="color:#00f">www.gemateknik.co.id</span>':''}</div></td></tr></table><div class="rule"></div>
  <table class="meta"><tr><td class="label">No</td><td class="colon">:</td><td>${e(q.no)}</td></tr><tr><td>Perihal</td><td>:</td><td>${e(q.perihal||'-')}</td></tr></table><div class="recipient"><p>Kepada Yth ,</p><p><b>${e(q.customer)}</b></p>${q.city?`<p>Di</p><p>${e(q.city)}</p>`:''}${q.attention?`<p style="margin-top:9pt"><b>U/P : ${e(q.attention)}</b></p>`:''}</div><div class="opening"><p>Dengan hormat,</p><p>${e(q.opening)}</p></div>
  <table class="items"><thead><tr><th class="no">No</th><th class="desc">${q.type==='Equipment'?'Nama Barang':'Keterangan'}</th><th>Harga/Unit</th><th class="qty">Jumlah</th><th>Total harga</th></tr></thead><tbody>${rows}${summary}</tbody></table><div class="terms"><p>${q.type==='Material'?'Kondisi Penawaran':q.type==='Jasa'?'Catatan':'Notes'} &nbsp;:</p><ul>${terms.map((x:string)=>`<li>-&nbsp;&nbsp;${e(x)}</li>`).join('')}</ul></div><div class="closing">Demikian penawaran harga ini kami buat, atas kerjasamanya kami ucapkan terimakasih.</div><div class="sign"><p>${e(q.signCity)}, ${dt}</p><p>PT. Gema Teknik Perkasa</p><div class="space"></div><p class="signer">${e(q.signer)}</p></div></body></html>`;
};

export const downloadQuotationWordDocument = async (quotation:any, filename:string) => { const content=await generateQuotationWordDocument(quotation), blob=new Blob(['\ufeff',content],{type:'application/msword'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url); };
