import gmLogo from 'figma:asset/661f558dc14c79fa090b7039a885f26b843f5c04.png';

const esc = (v: unknown) => String(v ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const dataUrl = async (url: string) => { const blob = await (await fetch(url)).blob(); return await new Promise<string>((ok, no) => { const r = new FileReader(); r.onload = () => ok(String(r.result)); r.onerror = no; r.readAsDataURL(blob); }); };
const dateId = (v: unknown) => new Date(String(v || Date.now())).toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' });
const header = (logo: string) => `<table class="head"><tr><td class="logo"><img src="${logo}"></td><td><div class="company">GEMA TEKNIK PERKASA</div><div class="business">REFRACTORY FURNACE AND BOILER</div><div class="contact">Jl. Nurushoba II No 13 Setia Mekar Tambun Selatan Bekasi 17510<br>Phone : 085 100 420 221, 021.88354 139 &nbsp; Fax : 021.88354 139<br>Email : <span>gemateknik@gmail.com</span></div></td></tr></table><div class="rule"></div>`;
const base = `@page{size:A4;margin:15mm 17mm}body{font-family:"Book Antiqua","Times New Roman",serif;font-size:10.5pt;line-height:1.3;color:#000}.head{width:100%;border-collapse:collapse}.head td{border:0;vertical-align:middle}.logo{width:105pt}.logo img{width:95pt}.company{font-size:17pt;font-weight:bold;font-style:italic}.business{font-size:10.5pt;font-weight:bold;font-style:italic}.contact{font-size:9pt;font-style:italic}.contact span{color:#00f}.rule{border-top:3pt solid #000;margin:5pt 0 10pt}.title{text-align:center;font-size:14pt;font-weight:bold;text-decoration:underline;margin:8pt 0 2pt}.number{text-align:center;font-weight:bold;margin:0 0 14pt}.meta{width:100%;border-collapse:collapse;margin-bottom:12pt}.meta td{border:0;padding:2pt}.meta .label{width:90pt}.meta .colon{width:10pt}.items{width:100%;border-collapse:collapse;table-layout:fixed}.items th,.items td{border:1pt solid #000;padding:4pt;vertical-align:top}.items th{text-align:center}.sign{width:100%;border-collapse:collapse;margin-top:26pt;page-break-inside:avoid}.sign td{border:0;text-align:center;width:33.33%}.space{height:55pt}.name{font-weight:bold;text-decoration:underline}.note{font-weight:bold;margin:8pt 0}.body{white-space:pre-wrap;text-align:justify}`;
const wordDocument = (title: string, body: string) => `<!DOCTYPE html><html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word"><head><meta charset="utf-8"><title>${esc(title)}</title><xml><w:WordDocument><w:View>Print</w:View><w:Zoom>100</w:Zoom></w:WordDocument></xml><style>${base}</style></head><body>${body}</body></html>`;
const save = (content: string, filename: string) => { const blob = new Blob(['\ufeff', content], { type: 'application/msword' }), url = URL.createObjectURL(blob), a = document.createElement('a'); a.href = url; a.download = filename; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url); };
export const printCorrespondence = (html: string) => { const win = window.open('', '_blank', 'width=900,height=1000'); if (!win) return; win.document.write(html); win.document.close(); win.focus(); setTimeout(() => win.print(), 300); };

export const generateSPKWord = async (spk: any) => {
  const logo = await dataUrl(gmLogo);
  const rows = spk.teknisiRows?.length
    ? spk.teknisiRows
    : (spk.teknisi || []).map((nama: string) => ({ nama, keterangan: '', qty: 1 }));
  const body = `${header(logo)}<p class="title">SURAT PERINTAH KERJA${spk.jenisSPK === 'Lembur' ? ' LEMBUR' : ''}</p><p class="number">No : ${esc(spk.noSPK || '-')}</p><table class="meta"><tr><td class="label">Hari / Tanggal</td><td class="colon">:</td><td>${esc(dateId(spk.tanggal))}</td></tr><tr><td>Jam Masuk</td><td>:</td><td>${esc(spk.jamMasuk || '-')}</td></tr><tr><td>Jam Keluar</td><td>:</td><td>${esc(spk.jamKeluar || '-')}</td></tr><tr><td>Project</td><td>:</td><td>${esc(spk.projectName || 'Internal Produksi')}</td></tr><tr><td>Pekerjaan</td><td>:</td><td><b>${esc(spk.pekerjaan || '-')}</b></td></tr></table><table class="items"><thead><tr><th style="width:7%">No</th><th style="width:31%">Nama</th><th>Keterangan / Tugas</th><th style="width:11%">Qty</th><th style="width:18%">Hasil</th></tr></thead><tbody>${rows.map((r: any, i: number) => `<tr><td style="text-align:center">${i + 1}</td><td>${esc(r.nama)}</td><td>${esc(r.keterangan || spk.pekerjaan || '')}</td><td style="text-align:center">${esc(r.qty || 1)}</td><td></td></tr>`).join('')}${Array.from({ length: Math.max(3, 8 - rows.length) }, () => '<tr><td>&nbsp;</td><td></td><td></td><td></td><td></td></tr>').join('')}</tbody></table>${spk.jenisSPK === 'Lembur' ? '<p class="note">Catatan: Kerja lembur tanpa SPK yang disetujui perusahaan tidak dapat dibayarkan.</p>' : ''}<table class="sign"><tr><td>Dibuat oleh,</td><td>Disetujui oleh,</td><td>Mengetahui,</td></tr><tr><td class="space"></td><td></td><td></td></tr><tr><td class="name">${esc(spk.dibuatOleh || spk.teknisi?.[0] || '-')}</td><td class="name">${esc(spk.disetujuiOleh || 'Syamsudin')}</td><td class="name">${esc(spk.mengetahui || 'Syamsudin')}</td></tr></table>`;
  return wordDocument(spk.noSPK || 'SPK', body);
};
export const downloadSPKWord = async (spk: any) => save(await generateSPKWord(spk), `SPK_${String(spk.noSPK || 'export').replace(/[\\/:*?"<>|]/g, '_')}.doc`);

export const generateMemoWord = async (memo: any) => {
  const logo = await dataUrl(gmLogo), bodyText = String(memo.isiSurat || '').replace(/<br\s*\/?>/gi, '\n').replace(/<[^>]+>/g, '');
  const body = `${header(logo)}<table class="meta"><tr><td class="label">Bekasi</td><td class="colon">:</td><td>${esc(dateId(memo.tanggalSurat))}</td></tr><tr><td>No.</td><td>:</td><td>${esc(memo.noSurat || '-')}</td></tr><tr><td>Perihal</td><td>:</td><td><b>${esc(memo.perihal || memo.jenisSurat || 'Memo')}</b></td></tr></table><div style="margin:14pt 0"><p>Kepada Yth,</p><p><b>${esc(memo.tujuan || '-')}</b></p>${memo.upPerson ? `<p>U/P : ${esc(memo.upPerson)}</p>` : ''}</div><div class="body">${esc(bodyText || `Dengan hormat,\n\nSehubungan dengan ${memo.perihal || 'keperluan operasional'}, bersama ini kami sampaikan memo untuk dapat ditindaklanjuti sebagaimana mestinya.\n\nDemikian disampaikan. Atas perhatian dan kerja samanya kami ucapkan terima kasih.`)}</div><table class="sign" style="margin-left:auto;width:42%"><tr><td>Hormat kami,<br>PT. Gema Teknik Perkasa</td></tr><tr><td class="space"></td></tr><tr><td class="name">${esc(memo.penandatangan || 'Syamsudin')}</td></tr></table>`;
  return wordDocument(memo.noSurat || 'Memo', body);
};
export const downloadMemoWord = async (memo: any) => save(await generateMemoWord(memo), `Memo_${String(memo.noSurat || 'export').replace(/[\\/:*?"<>|]/g, '_')}.doc`);
