// Sample Data Collection Loader - Real Project Data
// Based on: Repair Furnace Batubara - PT Starmortar Subang

export const loadStarmortarBOMData = () => {
  return {
    noKoleksi: "KOL-2026-0001",
    namaResponden: "PT Starmortar",
    kategori: "Survey",
    tanggalPengumpulan: "2026-02-11",
    lokasi: "Subang, Indonesia",
    namaKolektor: "Aji",
    tipePekerjaan: "Pasang baru",
    jenisKontrak: "Subcontractor",
    notes: "Repair Furnace Batubara - Thermal drying segment. Project duration: 14 days. Rev: 0",
    status: "Draft" as const,
    priority: "High" as const,
    tags: ["BOM", "Furnace Repair", "Thermal Drying", "Subang"],
    materials: [
      // Dinding Utara Materials
      {
        id: "MAT-001",
        materialName: "LR 68 (Dinding Utara Thk 600mm)",
        qtyEstimate: 5170,
        qtyActual: 5700,
        unit: "Kgs",
        supplier: "PT Gema Teknik",
      },
      {
        id: "MAT-002",
        materialName: "LW 1300 (Dinding Utara Thk 600mm)",
        qtyEstimate: 1948,
        qtyActual: 2150,
        unit: "Kgs",
        supplier: "PT Gema Teknik",
      },
      {
        id: "MAT-003",
        materialName: "Calcium Silica Board 50x500x1000mm (Utara)",
        qtyEstimate: 30,
        qtyActual: 33,
        unit: "Pcs",
        supplier: "PT Gema Teknik",
      },
      {
        id: "MAT-004",
        materialName: "Ceramic fiber paper 3x1200x20000mm 1260°C (Utara)",
        qtyEstimate: 0.3,
        qtyActual: 0.3,
        unit: "Roll",
        supplier: "PT Gema Teknik",
      },
      {
        id: "MAT-005",
        materialName: "LR 68 (Dinding Utara Thk 300mm)",
        qtyEstimate: 1521,
        qtyActual: 1675,
        unit: "Kgs",
        supplier: "PT Gema Teknik",
      },
      {
        id: "MAT-006",
        materialName: "SS Anchor 304 Y Las Dia.12x420mm (Utara)",
        qtyEstimate: 67,
        qtyActual: 69,
        unit: "Pcs",
        supplier: "PT Gema Teknik",
      },
      {
        id: "MAT-007",
        materialName: "SS Anchor 304 Y Las Dia.12x520mm (Utara)",
        qtyEstimate: 37,
        qtyActual: 38,
        unit: "Pcs",
        supplier: "PT Gema Teknik",
      },
      // Dinding Barat Materials
      {
        id: "MAT-008",
        materialName: "LR 68 (Dinding Barat Thk 600mm)",
        qtyEstimate: 7468,
        qtyActual: 8225,
        unit: "Kgs",
        supplier: "PT Gema Teknik",
      },
      {
        id: "MAT-009",
        materialName: "LW 1300 (Dinding Barat Thk 600mm)",
        qtyEstimate: 2814,
        qtyActual: 3100,
        unit: "Kgs",
        supplier: "PT Gema Teknik",
      },
      {
        id: "MAT-010",
        materialName: "Calcium Silica Board 50x500x1000mm (Barat)",
        qtyEstimate: 43,
        qtyActual: 48,
        unit: "Pcs",
        supplier: "PT Gema Teknik",
      },
      {
        id: "MAT-011",
        materialName: "Ceramic fiber paper 3x1200x20000mm 1260°C (Barat)",
        qtyEstimate: 0.3,
        qtyActual: 0.3,
        unit: "Roll",
        supplier: "PT Gema Teknik",
      },
      {
        id: "MAT-012",
        materialName: "LR 68 (Dinding Barat Thk 300mm)",
        qtyEstimate: 2119,
        qtyActual: 2350,
        unit: "Kgs",
        supplier: "PT Gema Teknik",
      },
      {
        id: "MAT-013",
        materialName: "SS Anchor 304 Y Las Dia.12x420mm (Barat)",
        qtyEstimate: 97,
        qtyActual: 99,
        unit: "Pcs",
        supplier: "PT Gema Teknik",
      },
      {
        id: "MAT-014",
        materialName: "SS Anchor 304 Y Las Dia.12x520mm (Barat)",
        qtyEstimate: 54,
        qtyActual: 55,
        unit: "Pcs",
        supplier: "PT Gema Teknik",
      },
      // Dinding Timur Materials
      {
        id: "MAT-015",
        materialName: "LR 68 (Dinding Timur Thk 600mm)",
        qtyEstimate: 7468,
        qtyActual: 8225,
        unit: "Kgs",
        supplier: "PT Gema Teknik",
      },
      {
        id: "MAT-016",
        materialName: "LW 1300 (Dinding Timur Thk 600mm)",
        qtyEstimate: 2814,
        qtyActual: 3100,
        unit: "Kgs",
        supplier: "PT Gema Teknik",
      },
      {
        id: "MAT-017",
        materialName: "Calcium Silica Board 50x500x1000mm (Timur)",
        qtyEstimate: 43,
        qtyActual: 48,
        unit: "Pcs",
        supplier: "PT Gema Teknik",
      },
      {
        id: "MAT-018",
        materialName: "Ceramic fiber paper 3x1200x20000mm 1260°C (Timur)",
        qtyEstimate: 0.3,
        qtyActual: 0.3,
        unit: "Roll",
        supplier: "PT Gema Teknik",
      },
      {
        id: "MAT-019",
        materialName: "LR 68 (Dinding Timur Thk 300mm)",
        qtyEstimate: 2119,
        qtyActual: 2350,
        unit: "Kgs",
        supplier: "PT Gema Teknik",
      },
      {
        id: "MAT-020",
        materialName: "SS Anchor 304 Y Las Dia.12x420mm (Timur)",
        qtyEstimate: 97,
        qtyActual: 99,
        unit: "Pcs",
        supplier: "PT Gema Teknik",
      },
      {
        id: "MAT-021",
        materialName: "SS Anchor 304 Y Las Dia.12x520mm (Timur)",
        qtyEstimate: 54,
        qtyActual: 55,
        unit: "Pcs",
        supplier: "PT Gema Teknik",
      },
      // Additional Materials
      {
        id: "MAT-022",
        materialName: "SS 304 Round bar 12x6000mm",
        qtyEstimate: 10,
        qtyActual: 10,
        unit: "Pcs",
        supplier: "PT Gema Teknik",
      },
      {
        id: "MAT-023",
        materialName: "Ceramic fiber blanket 25x610x7200mm 128 kg/m³ 1260°C",
        qtyEstimate: 2,
        qtyActual: 2,
        unit: "Roll",
        supplier: "PT Gema Teknik",
      },
    ],
    dataFields: [
      {
        fieldName: "Drawing Reference",
        fieldValue: "No Drawing",
        fieldType: "Text" as const,
      },
      {
        fieldName: "Project Segment",
        fieldValue: "Thermal drying",
        fieldType: "Text" as const,
      },
      {
        fieldName: "Total Surface",
        fieldValue: "17.073 m²",
        fieldType: "Text" as const,
      },
      {
        fieldName: "Total Weight Installed",
        fieldValue: "33,978 Kgs (14.866 m³)",
        fieldType: "Text" as const,
      },
      {
        fieldName: "Total Weight Delivered",
        fieldValue: "37,432 Kgs (16.381 m³)",
        fieldType: "Text" as const,
      },
      {
        fieldName: "Contract Partner",
        fieldValue: "-",
        fieldType: "Text" as const,
      },
    ],
  };
};

export const loadStarmortarProjectData = () => {
  return {
    noKoleksi: "KOL-2026-0002",
    namaResponden: "PT Starmortar",
    kategori: "Survey",
    tanggalPengumpulan: "2026-02-18",
    lokasi: "Subang, Indonesia",
    namaKolektor: "Anwar & Aji",
    tipePekerjaan: "Pasang baru",
    jenisKontrak: "Subcontractor",
    notes: "Data Persiapan Pekerjaan Proyek: Repair Furnace Boiler - Duration 14 hari. Dibuat oleh: Anwar & Aji. Mengetahui: Bpk. Alois. Rev: 0",
    status: "Draft" as const,
    priority: "High" as const,
    tags: ["Project Data", "Furnace Repair", "Boiler", "Subang"],
    // Manpower
    manpower: [
      {
        id: "MP-001",
        position: "Supervisor",
        quantity: 1,
        duration: 14,
        notes: "Overall project supervision",
      },
      {
        id: "MP-002",
        position: "QC (Quality Control)",
        quantity: 1,
        duration: 14,
        notes: "Quality inspection and control",
      },
      {
        id: "MP-003",
        position: "Safety Officer",
        quantity: 1,
        duration: 14,
        notes: "Safety management and compliance",
      },
      {
        id: "MP-004",
        position: "Team Leader",
        quantity: 1,
        duration: 14,
        notes: "Field team coordination",
      },
      {
        id: "MP-005",
        position: "Driver",
        quantity: 1,
        duration: 14,
        notes: "Material and crew transportation",
      },
      {
        id: "MP-006",
        position: "Nozzleman",
        quantity: 1,
        duration: 14,
        notes: "Gunning/spraying operation",
      },
      {
        id: "MP-007",
        position: "Welder",
        quantity: 1,
        duration: 14,
        notes: "Welding anchor installation",
      },
      {
        id: "MP-008",
        position: "Skilled Worker",
        quantity: 3,
        duration: 14,
        notes: "Installation and finishing work",
      },
      {
        id: "MP-009",
        position: "Helper",
        quantity: 5,
        duration: 14,
        notes: "Support work and material handling",
      },
      {
        id: "MP-010",
        position: "Local Worker",
        quantity: 2,
        duration: 14,
        notes: "Additional local support",
      },
    ],
    // Schedule
    schedule: [
      {
        id: "SCH-001",
        activityName: "Persiapan Kerja",
        startDate: "2026-02-18",
        endDate: "2026-02-18",
        area: "Site Preparation",
        notes: "Initial site preparation and setup",
      },
      {
        id: "SCH-002",
        activityName: "Mock Up",
        startDate: "2026-02-19",
        endDate: "2026-02-19",
        area: "Quality Control",
        notes: "Sample installation for approval",
      },
      {
        id: "SCH-003",
        activityName: "Bongkar Material Lama",
        startDate: "2026-02-20",
        endDate: "2026-02-26",
        area: "Dinding Utara, Barat, Timur",
        notes: "Demolition of existing material - 7 days",
      },
      {
        id: "SCH-004",
        activityName: "Cleaning Surface",
        startDate: "2026-02-27",
        endDate: "2026-02-27",
        area: "All Walls",
        notes: "Surface preparation and cleaning",
      },
      {
        id: "SCH-005",
        activityName: "Pemasangan Anchor",
        startDate: "2026-02-28",
        endDate: "2026-03-02",
        area: "All Walls",
        notes: "Anchor installation - 3 days",
      },
      {
        id: "SCH-006",
        activityName: "Pemasangan Scaffolding",
        startDate: "2026-03-03",
        endDate: "2026-03-04",
        area: "All Walls",
        notes: "Scaffolding installation - 2 days",
      },
      {
        id: "SCH-007",
        activityName: "Pemasangan Castable",
        startDate: "2026-03-05",
        endDate: "2026-03-09",
        area: "Dinding Utara, Barat, Timur",
        notes: "Castable installation - 5 days",
      },
      {
        id: "SCH-008",
        activityName: "Curing",
        startDate: "2026-03-10",
        endDate: "2026-03-10",
        area: "All Walls",
        notes: "Curing process",
      },
      {
        id: "SCH-009",
        activityName: "Finishing",
        startDate: "2026-03-11",
        endDate: "2026-03-11",
        area: "All Walls",
        notes: "Final finishing work",
      },
      {
        id: "SCH-010",
        activityName: "Inspeksi Pekerjaan",
        startDate: "2026-03-12",
        endDate: "2026-03-12",
        area: "Quality Control",
        notes: "Final inspection",
      },
      {
        id: "SCH-011",
        activityName: "Dry Out",
        startDate: "2026-03-13",
        endDate: "2026-03-14",
        area: "Per Manufacturer",
        notes: "Follow manufacturer specification",
      },
    ],
    // Equipment
    equipment: [
      {
        id: "EQ-001",
        equipmentName: "Mixer Paddle",
        quantity: 1,
        unit: "Unit",
        status: "Available" as const,
        notes: "Material mixing",
      },
      {
        id: "EQ-002",
        equipmentName: "Vibrator",
        quantity: 2,
        unit: "Unit",
        status: "Available" as const,
        notes: "Concrete vibration",
      },
      {
        id: "EQ-003",
        equipmentName: "Trafo Las (Welding Transformer)",
        quantity: 1,
        unit: "Unit",
        status: "Available" as const,
        notes: "Welding anchor",
      },
      {
        id: "EQ-004",
        equipmentName: "Jack Hammer Angin",
        quantity: 2,
        unit: "Unit",
        status: "Available" as const,
        notes: "Pneumatic demolition",
      },
      {
        id: "EQ-005",
        equipmentName: "Jack Hammer Listrik",
        quantity: 1,
        unit: "Unit",
        status: "Available" as const,
        notes: "Electric demolition",
      },
      {
        id: "EQ-006",
        equipmentName: "Gerinda (Grinder)",
        quantity: 2,
        unit: "Unit",
        status: "Available" as const,
        notes: "Cutting and grinding",
      },
      {
        id: "EQ-007",
        equipmentName: "Cutting Brick + Blade",
        quantity: 1,
        unit: "Unit",
        status: "Available" as const,
        notes: "Brick cutting",
      },
      {
        id: "EQ-008",
        equipmentName: "Hand Mixer",
        quantity: 1,
        unit: "Unit",
        status: "Available" as const,
        notes: "Small batch mixing",
      },
      {
        id: "EQ-009",
        equipmentName: "Gunning Set",
        quantity: 1,
        unit: "Unit",
        status: "Available" as const,
        notes: "Gunning application",
      },
      {
        id: "EQ-010",
        equipmentName: "Blower",
        quantity: 2,
        unit: "Unit",
        status: "Available" as const,
        notes: "Air circulation",
      },
    ],
    // Consumables
    consumables: [
      {
        id: "CON-001",
        itemName: "Triplek 12 mm",
        quantity: 15,
        unit: "Lembar",
        category: "Tools" as const,
      },
      {
        id: "CON-002",
        itemName: "Triplek 3 mm",
        quantity: 3,
        unit: "Lembar",
        category: "Tools" as const,
      },
      {
        id: "CON-003",
        itemName: "Kaso 4x6",
        quantity: 15,
        unit: "Ikat",
        category: "Tools" as const,
      },
      {
        id: "CON-004",
        itemName: "Paku 7",
        quantity: 10,
        unit: "Kg",
        category: "Tools" as const,
      },
      {
        id: "CON-005",
        itemName: "Paku 5",
        quantity: 10,
        unit: "Kg",
        category: "Tools" as const,
      },
      {
        id: "CON-006",
        itemName: "Paku GRC",
        quantity: 5,
        unit: "Dus",
        category: "Tools" as const,
      },
      {
        id: "CON-007",
        itemName: "Kawat Stainless ikat",
        quantity: 5,
        unit: "Kg",
        category: "Tools" as const,
      },
      {
        id: "CON-008",
        itemName: "Karung sampah",
        quantity: 150,
        unit: "Pcs",
        category: "Other" as const,
      },
      {
        id: "CON-009",
        itemName: "Jumbo bag",
        quantity: 200,
        unit: "Pcs",
        category: "Other" as const,
      },
      {
        id: "CON-010",
        itemName: "Diamond cup",
        quantity: 5,
        unit: "Pcs",
        category: "Tools" as const,
      },
      {
        id: "CON-011",
        itemName: "Kawat Las 304",
        quantity: 10,
        unit: "Kg",
        category: "Tools" as const,
      },
      {
        id: "CON-012",
        itemName: "Pipa Scaffolding 2,5 m",
        quantity: 20,
        unit: "Pcs",
        category: "Tools" as const,
      },
      {
        id: "CON-013",
        itemName: "Jekbesh",
        quantity: 30,
        unit: "Pcs",
        category: "Tools" as const,
      },
      {
        id: "CON-014",
        itemName: "Klem scaffolding",
        quantity: 50,
        unit: "Pcs",
        category: "Tools" as const,
      },
      {
        id: "CON-015",
        itemName: "Bluesheet",
        quantity: 1,
        unit: "Pcs",
        category: "Other" as const,
      },
      {
        id: "CON-016",
        itemName: "Lain-lain",
        quantity: 5,
        unit: "Jt",
        category: "Other" as const,
      },
    ],
    // Data Fields
    dataFields: [
      {
        fieldName: "Project Name",
        fieldValue: "Repair Furnace Boiler",
        fieldType: "Text" as const,
      },
      {
        fieldName: "Duration",
        fieldValue: "14 Hari",
        fieldType: "Text" as const,
      },
      {
        fieldName: "Work Shift",
        fieldValue: "1 shift",
        fieldType: "Text" as const,
      },
      {
        fieldName: "Total Manpower",
        fieldValue: "17 Orang",
        fieldType: "Number" as const,
      },
      {
        fieldName: "Medical Check Up",
        fieldValue: "Required",
        fieldType: "Text" as const,
      },
      {
        fieldName: "Working Permit",
        fieldValue: "Customer (User)",
        fieldType: "Text" as const,
      },
      {
        fieldName: "Water Supply pH",
        fieldValue: "6 - 8 (User)",
        fieldType: "Text" as const,
      },
      {
        fieldName: "Created By",
        fieldValue: "Anwar & Aji",
        fieldType: "Text" as const,
      },
      {
        fieldName: "Approved By",
        fieldValue: "Bpk. Alois",
        fieldType: "Text" as const,
      },
      {
        fieldName: "Scope - Material Supply",
        fieldValue: "Gema",
        fieldType: "Text" as const,
      },
      {
        fieldName: "Scope - Anchor Installation",
        fieldValue: "Gema",
        fieldType: "Text" as const,
      },
      {
        fieldName: "Scope - Castable Installation",
        fieldValue: "Gema",
        fieldType: "Text" as const,
      },
      {
        fieldName: "Scope - Dry Out",
        fieldValue: "Gema",
        fieldType: "Text" as const,
      },
      {
        fieldName: "Scope - Transport",
        fieldValue: "Gema",
        fieldType: "Text" as const,
      },
      {
        fieldName: "Scope - Accommodation",
        fieldValue: "Gema",
        fieldType: "Text" as const,
      },
      {
        fieldName: "Scope - Safety Equipment",
        fieldValue: "Gema",
        fieldType: "Text" as const,
      },
      {
        fieldName: "Pekerjaan 1",
        fieldValue: "Dinding Utara 2775x2700mm Thk: 600-900mm",
        fieldType: "Text" as const,
      },
      {
        fieldName: "Pekerjaan 2",
        fieldValue: "Dinding Barat 3900x2775mm Thk: 600-900mm",
        fieldType: "Text" as const,
      },
      {
        fieldName: "Pekerjaan 3",
        fieldValue: "Dinding Timur 3900x2775mm Thk: 600-900mm",
        fieldType: "Text" as const,
      },
      {
        fieldName: "Notes",
        fieldValue: "Material existing brick diganti dengan castable",
        fieldType: "Text" as const,
      },
    ],
  };
};

// Combined summary
export const getStarmortarProjectSummary = () => {
  const bomData = loadStarmortarBOMData();
  const projectData = loadStarmortarProjectData();

  return {
    projectName: "Repair Furnace Batubara - PT Starmortar",
    location: "Subang, Indonesia",
    duration: "14 Days (18 Feb - 3 Mar 2026)",
    totalMaterials: bomData.materials.length,
    totalManpower: 17,
    totalEquipment: 10,
    totalConsumables: 16,
    totalScheduleItems: 11,
    totalWeightInstalled: "33,978 Kgs",
    totalWeightDelivered: "37,432 Kgs",
    workAreas: [
      "Dinding Utara 2775x2700mm (Thk: 600-900mm)",
      "Dinding Barat 3900x2775mm (Thk: 600-900mm)",
      "Dinding Timur 3900x2775mm (Thk: 600-900mm)",
    ],
  };
};
